In [30]:
import pyautogui
import numpy as np
import pywinctl as pwc
from PIL import Image
from mss import mss, tools

import time

In [25]:
# Get the application window
window_name = 'rscplus (RSC Preservation; friqi)'
window = pwc.getWindowsWithTitle(window_name)[0]

# Focus on the window
window.activate()

# Define the region of the window (x, y, width, height)
SEARCH_REGION = (window.left, window.top, window.width, window.height)

# Take a screenshot of the window
sct = mss()


In [16]:
image.shape

(1440, 2170, 4)

In [17]:
window.width

1085

In [18]:
window.height

720

In [38]:
def scale(window_width, window_height, screenshot_width,
          screenshot_height, x, y):
    print(window_width, window_height, screenshot_width,
          screenshot_height, x, y)
#     raise
    return (x * window_width / screenshot_width,
            y * window_height / screenshot_height)

In [23]:
def get_screenshot():
    screenshot = sct.grab(MONITOR)

    # for debugging - to print out output
    # output = "sct-{top}x{left}_{width}x{height}.png".format(**MONITOR)
    # tools.to_png(screenshot.rgb, screenshot.size, output="/tmp/{}".format(output))
    return screenshot

In [37]:
def cut_tree():
    window.activate()
    # Define the color you want to detect (in RGB format)
    wood_of_tree = (145, 80, 39)
    screenshot = get_screenshot()

    # Convert the screenshot to a numpy array
    image = np.array(screenshot)

    BROWN_COLOR_RANGE = {
        # "R": (150, 200),
        # "G": (100, 150),
        # "B": (30, 50)
        "R": (150, 200),
        "G": (100, 150),
        "B": (50, 100)
    }

    COLOR_RANGE = BROWN_COLOR_RANGE
    mask = (
        (image[:,:,0] >= COLOR_RANGE["R"][0]) & (image[:,:,0] <= COLOR_RANGE["R"][1]) &
        (image[:,:,1] >= COLOR_RANGE["G"][0]) & (image[:,:,1] <= COLOR_RANGE["G"][1]) &
        (image[:,:,2] >= COLOR_RANGE["B"][0]) & (image[:,:,2] <= COLOR_RANGE["B"][1])
    )


    # Search for the target color
    indices = np.where(mask)

    # If the color is found, move the mouse to the first occurrence and click
    if indices[0].size > 0:
        y, x = indices[0][0], indices[1][0]
        window_width, window_height = SEARCH_REGION[2], SEARCH_REGION[3]
        screenshot_width, screenshot_height = image.shape[1], image.shape[0]

        x, y = scale(window_width, window_height, screenshot_width, screenshot_height, x, y)

        screen_x = x + SEARCH_REGION[0]
        screen_y = y + SEARCH_REGION[1]
        print('screen x / y', screen_x, screen_y)
        pyautogui.moveTo(screen_x, screen_y)
        pyautogui.click()
        print(f"Color found and clicked at ({screen_x}, {screen_y})")
    else:
        print("Color not found")
    return

In [39]:
cut_tree()

1085 720 2170 1440 1176 1044
screen x / y 631.0 591.0
Color found and clicked at (631.0, 591.0)


In [36]:
count = 0
while count < 60:
    cut_tree()
    time.sleep(3)
    count += 1

1085 720 1440 2170 1172 1048


RuntimeError: No active exception to reraise

In [40]:
### TEST BELOW ###

In [57]:
    window.activate()
    # Define the color you want to detect (in RGB format)
    wood_of_tree = (145, 80, 39)
    screenshot = get_screenshot()

    # Convert the screenshot to a numpy array
    image = np.array(screenshot)

    BROWN_COLOR_RANGE = {
        # "R": (150, 200),
        # "G": (100, 150),
        # "B": (30, 50)
        "R": (150, 200),
        "G": (100, 150),
        "B": (50, 100)
    }

    COLOR_RANGE = BROWN_COLOR_RANGE
    mask = (
        (image[:,:,0] >= COLOR_RANGE["R"][0]) & (image[:,:,0] <= COLOR_RANGE["R"][1]) &
        (image[:,:,1] >= COLOR_RANGE["G"][0]) & (image[:,:,1] <= COLOR_RANGE["G"][1]) &
        (image[:,:,2] >= COLOR_RANGE["B"][0]) & (image[:,:,2] <= COLOR_RANGE["B"][1])
    )


    # Search for the target color
    indices = np.where(mask)

    # If the color is found, move the mouse to the first occurrence and click
    if indices[0].size > 0:
        y, x = indices[0][0], indices[1][0]
        window_width, window_height = SEARCH_REGION[2], SEARCH_REGION[3]
        # screenshot_width, screenshot_height = image.shape[0], image.shape[1]
        screenshot_width, screenshot_height = image.shape[1], image.shape[0]

        x, y = scale(window_width, window_height, screenshot_width, screenshot_height, x, y)

        screen_x = x + SEARCH_REGION[0]
        screen_y = y + SEARCH_REGION[1]
        print('screen x / y', screen_x, screen_y)

1085 720 2170 1440 1948 1040
screen x / y 1017.0 589.0


In [58]:
indices

(array([1040, 1040, 1040, ..., 1347, 1347, 1347]),
 array([1948, 1949, 1950, ..., 1473, 1474, 1475]))

In [60]:
image[indices[0][0]][indices[1][0]]

array([189, 104,  56, 255], dtype=uint8)

In [49]:
image.shape

(1440, 2170, 4)

In [50]:
indices[0][0], indices[1][0]

(1236, 1228)